<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Core Metadata -->
    <AssemblyName>build_anglesharp</AssemblyName>
    <RootNamespace>build_anglesharp</RootNamespace>
    <Authors>Woz</Authors>
    <!-- Your name or organization -->
    <Company>WozDev</Company>
    <!-- Organization -->
    <Description>Packages the AngleSharp assembly for use in projects requiring html parsing or manipulation.</Description>
    <PackageId>build-anglesharp</PackageId>
    <!-- Unique Package ID -->
    <Version>1.0.0</Version>
    <!-- SemVer format -->
    <Copyright>Copyright (c) WozDev 2025</Copyright>
    <!-- Copyright notice -->
    <RepositoryUrl>https://github.com/WozDev/Woz-Assemblies</RepositoryUrl>
    <!-- Repository URL -->
    <RepositoryType>git</RepositoryType>
    <!-- Repository type -->
    <PackageTags>AngleSharp</PackageTags>
    <!-- Tags for discoverability -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!-- Optional README -->
    <!-- Packaging Settings -->
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <!-- Disabled for manual packing -->
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <!-- Same output path -->
    <TargetFramework>netstandard2.0</TargetFramework>
    <!-- Broad compatibility -->
    <!-- Additional Settings -->
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GeneratePathProperty>true</GeneratePathProperty>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <!-- Files to be included in nupkg file -->
    <None Include="README.md">
      <Pack>true</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="bin\Release\netstandard2.0\win-x64\AngleSharp.dll">
      <Pack>true</Pack>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackagePath>AngleSharp-lib/netstandard2.0/</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <!-- Package references for Magick.NET -->
    <PackageReference Include="AngleSharp" Version="1.5.0">
      <IncludeAssets>all</IncludeAssets>
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>